// restore ../datatests/ssbm/Physics_UpdateECBBones.xml
// load function Physics_UpdateECBBones
// trace address 0x8004254c
// trace address 0x80042554
// trace address 0x8004255c
// trace address 0x80042560
// trace address 0x800425f8

restore ../datatests/ssbm/Interrupt_Throw.xml
load function Interrupt_Throw

trace enable
option togglerule shiftand off
option inplaceops on
option indentincrement 2
decompile
print C
quit